export function stripTrailingNewline(code: string): string {
  return code.endsWith("\n") ? code.slice(0, -1) : code;
}

export function detectLanguage(fileName: string): string {
  const ext = fileName.split(".").pop()?.toLowerCase() ?? "";
  const map: Record<string, string> = {
    // JavaScript / TypeScript
    ts: "typescript",
    cts: "typescript",
    mts: "typescript",
    tsx: "tsx",
    js: "javascript",
    cjs: "javascript",
    mjs: "javascript",
    jsx: "jsx",
    // Systems / compiled
    go: "go",
    rs: "rust",
    c: "c",
    h: "c",
    cpp: "cpp",
    hpp: "cpp",
    cs: "csharp",
    java: "java",
    kt: "kotlin",
    kts: "kotlin",
    swift: "swift",
    scala: "scala",
    zig: "zig",
    nim: "nim",
    d: "d",
    // Scripting
    py: "python",
    rb: "ruby",
    pl: "perl",
    php: "php",
    lua: "lua",
    r: "r",
    jl: "julia",
    ex: "elixir",
    exs: "elixir",
    erl: "erlang",
    clj: "clojure",
    hs: "haskell",
    ml: "ocaml",
    mli: "ocaml",
    fs: "fsharp",
    fsx: "fsharp",
    dart: "dart",
    groovy: "groovy",
    // Shell
    sh: "bash",
    bash: "bash",
    zsh: "bash",
    fish: "fish",
    nu: "nushell",
    ps1: "powershell",
    bat: "bat",
    cmd: "bat",
    // Web / markup
    html: "html",
    htm: "html",
    xml: "xml",
    xsl: "xsl",
    css: "css",
    scss: "scss",
    sass: "sass",
    less: "less",
    vue: "vue",
    svelte: "svelte",
    astro: "astro",
    // Data / config
    json: "json",
    jsonc: "jsonc",
    json5: "json5",
    yaml: "yaml",
    yml: "yaml",
    toml: "toml",
    ini: "ini",
    csv: "csv",
    tsv: "tsv",
    env: "dotenv",
    // Markup / docs
    md: "markdown",
    mdx: "mdx",
    tex: "latex",
    rst: "rst",
    adoc: "asciidoc",
    // Query / data
    sql: "sql",
    graphql: "graphql",
    gql: "graphql",
    prisma: "prisma",
    // DevOps / infra
    dockerfile: "dockerfile",
    makefile: "makefile",
    tf: "terraform",
    tfvars: "terraform",
    hcl: "hcl",
    nix: "nix",
    // Protocol / schema
    proto: "proto",
    cue: "cue",
    // Other
    diff: "diff",
    vim: "viml",
    el: "emacs-lisp",
    wasm: "wasm",
    awk: "awk",
    sed: "sed",
  };
  return map[ext] || "text";
}
